//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelicaciesFood.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sfav
    {
        public int SfavID { get; set; }
        public string SfavName { get; set; }
        public string SfavPic { get; set; }
        public string SfavExplain { get; set; }
        public Nullable<int> MatureSeason { get; set; }
    }
}
