//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstSystem1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int FoodID { get; set; }
        public string FoodName { get; set; }
        public Nullable<int> FoodType { get; set; }
        public string FoodPicture { get; set; }
        public Nullable<int> FoodDifficulty { get; set; }
        public Nullable<decimal> CompletionTime { get; set; }
        public string Flavor { get; set; }
        public string CookingUtensils { get; set; }
        public string CookingStyle { get; set; }
        public string Mainmaterial { get; set; }
        public string Accessories { get; set; }
        public string FlowChart { get; set; }
        public Nullable<int> ThumbNumber { get; set; }
        public Nullable<int> Foodissuer { get; set; }
    
        public virtual User User { get; set; }
    }
}
